export const queryKeys = {
  circles: ['circles'] as const,
  myMembership: (circleId: string) => ['circles', circleId, 'my-membership'] as const,
  members: (circleId: string) => ['circles', circleId, 'members'] as const,
  guardianRelationships: (circleId: string) => ['circles', circleId, 'guardians'] as const,
  tasks: (circleId: string) => ['circles', circleId, 'tasks'] as const,
  task: (taskId: string) => ['tasks', taskId] as const,
  taskCompletions: (taskId: string) => ['tasks', taskId, 'completions'] as const,
  pendingValidations: (circleId: string) => ['circles', circleId, 'pending-validations'] as const,
  wallet: (memberId: string) => ['wallet', memberId] as const,
  circleWallets: (circleId: string) => ['circles', circleId, 'wallets'] as const,
  pointHistory: (memberId: string) => ['wallet', memberId, 'history'] as const,
  rewards: (circleId: string) => ['circles', circleId, 'rewards'] as const,
  redemptions: (circleId: string) => ['circles', circleId, 'redemptions'] as const,
  projects: (circleId: string) => ['circles', circleId, 'projects'] as const,
  projectTasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  projectMembers: (projectId: string) => ['projects', projectId, 'members'] as const,
  projectWallet: (projectId: string) => ['projects', projectId, 'wallet'] as const,
  promiseVotes: (projectId: string) => ['projects', projectId, 'promise-votes'] as const,
  activity: (circleId: string) => ['circles', circleId, 'activity'] as const,
  notifications: ['notifications'] as const,
  invitations: (circleId: string) => ['circles', circleId, 'invitations'] as const,
} as const;
